# Numpy:応用編

## 12.1 ndarrayオブジェクトの内部構造
###12.1.1 Numpy dtypeの階層構造

In [1]:
ints = np.ones(10, dtype=np.uint16)
floats = np.ones(10, dtype=np.float32)
np.issubdtype(ints.dtype, np.integer)
np.issubdtype(floats.dtype, np.floating)

True

In [2]:
np.float64.mro()

[numpy.float64,
 numpy.floating,
 numpy.inexact,
 numpy.number,
 numpy.generic,
 float,
 object]

## 12.2 配列操作：応用編
### 12.2.1 配列の再作成

In [4]:
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [5]:
arr.reshape((4,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [6]:
arr = np.arange(15)

In [7]:
arr.reshape((5, -1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [8]:
arr = np.arange(15).reshape((5,3))
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [9]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### 12.2.2 CとFortranの順序の違い

In [10]:
arr = np.arange(12).reshape((3,4))

In [11]:
# C型のアクセス順序（デフォルト）
arr.ravel('C')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [12]:
# Fortran型のアクセス順序
arr.ravel('F')

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

### 12.2.3 配列の結合と分割

In [13]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

In [14]:
np.concatenate([arr1, arr2], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [15]:
np.concatenate([arr1, arr2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [16]:
np.vstack((arr1, arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [17]:
from numpy.random import randn
arr = randn(5, 2)
arr

array([[-1.04699882, -1.46535895],
       [-1.11392714,  0.34020857],
       [ 0.59557712, -0.40745468],
       [ 0.84243973, -0.60479551],
       [ 0.75714836, -0.50369907]])

In [18]:
first, second, third = np.split(arr, [1, 3])

In [19]:
first

array([[-1.04699882, -1.46535895]])

In [20]:
second

array([[-1.11392714,  0.34020857],
       [ 0.59557712, -0.40745468]])

In [21]:
third

array([[ 0.84243973, -0.60479551],
       [ 0.75714836, -0.50369907]])

### 12.2.4 要素の繰り返し : tile, repeat

In [22]:
arr = np.arange(3)

In [23]:
arr

array([0, 1, 2])

In [24]:
arr.repeat(3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [25]:
arr.repeat([2,3,4])

array([0, 0, 1, 1, 1, 2, 2, 2, 2])

In [26]:
arr = randn(2,2)
arr

array([[-1.65339971, -0.91067579],
       [ 0.13899885, -0.98572418]])

In [27]:
arr.repeat(2, axis=0)

array([[-1.65339971, -0.91067579],
       [-1.65339971, -0.91067579],
       [ 0.13899885, -0.98572418],
       [ 0.13899885, -0.98572418]])

In [28]:
# 軸を指定しないと、行列が平坦になる
arr.repeat(2)

array([-1.65339971, -1.65339971, -0.91067579, -0.91067579,  0.13899885,
        0.13899885, -0.98572418, -0.98572418])

In [29]:
np.tile(arr, 2)

array([[-1.65339971, -0.91067579, -1.65339971, -0.91067579],
       [ 0.13899885, -0.98572418,  0.13899885, -0.98572418]])

In [30]:
np.tile(arr, (2, 1))

array([[-1.65339971, -0.91067579],
       [ 0.13899885, -0.98572418],
       [-1.65339971, -0.91067579],
       [ 0.13899885, -0.98572418]])

In [32]:
np.tile(arr, (3, 2))

array([[-1.65339971, -0.91067579, -1.65339971, -0.91067579],
       [ 0.13899885, -0.98572418,  0.13899885, -0.98572418],
       [-1.65339971, -0.91067579, -1.65339971, -0.91067579],
       [ 0.13899885, -0.98572418,  0.13899885, -0.98572418],
       [-1.65339971, -0.91067579, -1.65339971, -0.91067579],
       [ 0.13899885, -0.98572418,  0.13899885, -0.98572418]])

### 12.2.5 ファンシーインデックス参照の別法 : takeとput

In [33]:
arr = np.arange(10) * 100
inds = [7, 1, 2, 6]
arr[inds]

array([700, 100, 200, 600])

In [34]:
arr.take(inds)

array([700, 100, 200, 600])

In [35]:
arr

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [36]:
arr.put(inds, 42)

In [37]:
arr

array([  0,  42,  42, 300, 400, 500,  42,  42, 800, 900])

In [38]:
arr = randn(2, 4)
inds = [2,0,2,1]

In [39]:
arr

array([[-0.11091516,  0.20055939,  1.41933872, -0.07490783],
       [-0.50697903, -0.40781569, -0.3710825 ,  1.74456808]])

In [40]:
arr.take(inds, axis=1)

array([[ 1.41933872, -0.11091516,  1.41933872,  0.20055939],
       [-0.3710825 , -0.50697903, -0.3710825 , -0.40781569]])

## 12.3 ブロードキャスト

In [41]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [42]:
arr*4

array([ 0,  4,  8, 12, 16])

In [44]:
arr = randn(4, 3)
arr

array([[-0.55251232,  0.04182122, -0.52726885],
       [-0.24532146,  0.33145427,  0.66179337],
       [ 0.79592487,  0.08157655,  0.37323218],
       [-1.05973138, -0.438998  ,  1.04672001]])

In [45]:
arr.mean(0)

array([-0.26541007,  0.00396351,  0.38861918])

In [46]:
demeaned = arr - arr.mean(0)
demeaned

array([[-0.28710225,  0.03785771, -0.91588803],
       [ 0.02008861,  0.32749076,  0.27317419],
       [ 1.06133494,  0.07761304, -0.015387  ],
       [-0.79432131, -0.44296151,  0.65810083]])

In [51]:
a = np.arange(15).reshape((5,3))
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [58]:
b = np.arange(3).reshape(1,3)
b

array([[0, 1, 2]])

In [59]:
a-b

array([[ 0,  0,  0],
       [ 3,  3,  3],
       [ 6,  6,  6],
       [ 9,  9,  9],
       [12, 12, 12]])

### 12.3.1 他の軸へのブロードキャスト

## 12.4 ufuncの使い方
### 12.4.1 ufuncインスタンスメソッド

In [62]:
arr = randn(5,5)
arr

array([[-0.11171172,  0.88323733,  0.56254679,  0.4576093 ,  0.6852918 ],
       [-0.94053647,  1.06957951, -0.59505347, -0.16079628, -0.37762215],
       [ 0.51937708,  0.959249  ,  0.50911437, -0.74801822,  2.07539436],
       [-0.75399545, -0.37958986, -2.00300491, -0.53893725,  0.19736582],
       [ 0.76353849,  0.32031721,  0.82842845, -0.08416755, -0.53336699]])

In [63]:
# 1,3,5 行目だけソート
arr[::2].sort(1)
arr

array([[-0.11171172,  0.4576093 ,  0.56254679,  0.6852918 ,  0.88323733],
       [-0.94053647,  1.06957951, -0.59505347, -0.16079628, -0.37762215],
       [-0.74801822,  0.50911437,  0.51937708,  0.959249  ,  2.07539436],
       [-0.75399545, -0.37958986, -2.00300491, -0.53893725,  0.19736582],
       [-0.53336699, -0.08416755,  0.32031721,  0.76353849,  0.82842845]])

In [64]:
# ソート済み確認に使う部分配列（０番目からn-1番目を切り出す）
arr[:,:-1] 

array([[-0.11171172,  0.4576093 ,  0.56254679,  0.6852918 ],
       [-0.94053647,  1.06957951, -0.59505347, -0.16079628],
       [-0.74801822,  0.50911437,  0.51937708,  0.959249  ],
       [-0.75399545, -0.37958986, -2.00300491, -0.53893725],
       [-0.53336699, -0.08416755,  0.32031721,  0.76353849]])

In [65]:
# ソート済み確認に使う部分配列（1番目からn番目を切り出す）
arr[:,1:] 

array([[ 0.4576093 ,  0.56254679,  0.6852918 ,  0.88323733],
       [ 1.06957951, -0.59505347, -0.16079628, -0.37762215],
       [ 0.50911437,  0.51937708,  0.959249  ,  2.07539436],
       [-0.37958986, -2.00300491, -0.53893725,  0.19736582],
       [-0.08416755,  0.32031721,  0.76353849,  0.82842845]])

In [66]:
# ソートしてない行は、右側が大きいことが保証されないのでFalseが出る
arr[:,:-1] < arr[:, 1:]

array([[ True,  True,  True,  True],
       [ True, False,  True, False],
       [ True,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True,  True,  True]], dtype=bool)

In [67]:
np.logical_and.reduce(arr[:, :-1] < arr[:, 1:], axis=1)

array([ True, False,  True, False,  True], dtype=bool)

In [68]:
arr = np.arange(10)
np.add.reduceat(arr, [0, 5, 8])

array([10, 18, 17])

In [69]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
arr = np.multiply.outer(np.arange(4), np.arange(5))
arr

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4],
       [ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12]])

In [71]:
np.add.reduceat(arr, [0, 2, 4], axis=1)

array([[ 0,  0,  0],
       [ 1,  5,  4],
       [ 2, 10,  8],
       [ 3, 15, 12]])

### 12.4.2 独自定義のufunc

In [72]:
def add_elements(x, y):
    return x + y

In [73]:
add_them = np.frompyfunc(add_elements, 2, 1)

In [74]:
add_them(np.arange(8), np.arange(8))

array([0, 2, 4, 6, 8, 10, 12, 14], dtype=object)

In [75]:
# frompyfuncだとPythonオブジェクトの配列を返す
# numpy.vectorizeも似たような機能
add_them = np.vectorize(add_elements, otypes=[np.float64])
add_them(np.arange(8), np.arange(8))

array([  0.,   2.,   4.,   6.,   8.,  10.,  12.,  14.])

In [76]:
arr = randn(10000)
%timeit add_them(arr, arr)
%timeit np.add(arr, arr)

100 loops, best of 3: 2.08 ms per loop
The slowest run took 8.46 times longer than the fastest. This could mean that an intermediate result is being cached 
100000 loops, best of 3: 4.96 µs per loop


## 12.5 構造化配列とレコード配列

In [77]:
dtype = [('x', np.float64), ('y', np.int32)]
sarr = np.array([(1.5, 6), (np.pi, -2)], dtype=dtype)
sarr

array([(1.5, 6), (3.141592653589793, -2)], 
      dtype=[('x', '<f8'), ('y', '<i4')])

In [78]:
sarr[0]

(1.5, 6)

In [79]:
sarr[0]['y']

6

In [80]:
sarr['x']

array([ 1.5       ,  3.14159265])

### 12.5.1 ネストしたdtypeと多次元フィールド

In [81]:
dtype = [('x', np.int64, 3), ('y', np.int32)]
arr = np.zeros(4, dtype=dtype)
arr

array([([0, 0, 0], 0), ([0, 0, 0], 0), ([0, 0, 0], 0), ([0, 0, 0], 0)], 
      dtype=[('x', '<i8', (3,)), ('y', '<i4')])

In [82]:
arr['x']

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [83]:
dtype = [('x', [('a', 'f8'), ('b', 'f4')]), ('y', np.int32)]
data = np.array([((1, 2), 5), ((3, 4), 6)], dtype=dtype)
data['x']

array([(1.0, 2.0), (3.0, 4.0)], 
      dtype=[('a', '<f8'), ('b', '<f4')])

In [84]:
data

array([((1.0, 2.0), 5), ((3.0, 4.0), 6)], 
      dtype=[('x', [('a', '<f8'), ('b', '<f4')]), ('y', '<i4')])

In [85]:
data['x']['a']

array([ 1.,  3.])

In [86]:
data['y']

array([5, 6], dtype=int32)

## 12.6 ソートについてさらに詳しく

In [87]:
arr = randn(6)
arr

array([-0.35995807,  0.05649661,  0.37131182, -0.11941   , -1.86364994,
        1.0506024 ])

In [88]:
# ndarrayのsort()は配列自体を作り変える
arr.sort()

In [89]:
arr

array([-1.86364994, -0.35995807, -0.11941   ,  0.05649661,  0.37131182,
        1.0506024 ])

In [90]:
arr = randn(5)

In [91]:
arr

array([-0.29853155,  0.96411524, -0.77820451, -0.56451895, -0.53424385])

In [92]:
# numpy.sort()は、配列のコピーを返す
np.sort(arr)

array([-0.77820451, -0.56451895, -0.53424385, -0.29853155,  0.96411524])

In [93]:
arr = randn(3, 5)
arr

array([[ 1.38040822, -1.18192115,  0.90236432, -0.2914846 , -0.51500932],
       [ 0.87174129,  1.11774241, -2.27524051, -0.28360801, -1.14307175],
       [-2.16870783, -1.61686096, -0.62062522, -0.84278612,  0.97779781]])

In [94]:
arr.sort(axis=1)
arr

array([[-1.18192115, -0.51500932, -0.2914846 ,  0.90236432,  1.38040822],
       [-2.27524051, -1.14307175, -0.28360801,  0.87174129,  1.11774241],
       [-2.16870783, -1.61686096, -0.84278612, -0.62062522,  0.97779781]])

### 12.6.1 間接ソート：argsortとlexsort

In [95]:
values = np.array([5, 0, 1, 3, 2])
# 配列のソートする場合のindex
indexer = values.argsort()
indexer

array([1, 2, 4, 3, 0])

In [96]:
values[indexer]

array([0, 1, 2, 3, 5])

In [97]:
arr = randn(3, 5)
arr[0] = values
arr

array([[ 5.        ,  0.        ,  1.        ,  3.        ,  2.        ],
       [ 0.52228782, -0.48606292,  0.63426331,  0.06375331,  1.47411833],
       [ 0.89920646,  0.73812263, -2.13906612,  0.52293975,  0.76008761]])

In [98]:
arr[:, arr[0].argsort()]

array([[ 0.        ,  1.        ,  2.        ,  3.        ,  5.        ],
       [-0.48606292,  0.63426331,  1.47411833,  0.06375331,  0.52228782],
       [ 0.73812263, -2.13906612,  0.76008761,  0.52293975,  0.89920646]])

In [99]:
first_name = np.array(['Bob', 'Jane', 'Steve', 'Bill', 'Barbara'])
last_name = np.array(['Jones', 'Arnold', 'Arnold', 'Jones', 'Walters'])
sorter = np.lexsort((first_name, last_name))
zip(last_name[sorter], first_name[sorter])

[('Arnold', 'Jane'),
 ('Arnold', 'Steve'),
 ('Jones', 'Bill'),
 ('Jones', 'Bob'),
 ('Walters', 'Barbara')]

### 12.6.1 使用可能な他のソートアルゴリズム

In [100]:
values = np.array(['2:first', '2:second', '1:first', '1:second', '1:third'])
key = np.array([2, 2, 1, 1, 1])
indexer = key.argsort(kind='mergesort')
indexer

array([2, 3, 4, 0, 1])

In [101]:
values.take(indexer)

array(['1:first', '1:second', '1:third', '2:first', '2:second'], 
      dtype='|S8')

### 12.6.3 numpy.searchsorted : ソートされた配列内で要素を探す

In [102]:
# searchsortedを使うとソートされた配列内で二分探索ができる
arr = np.array([0, 1, 7, 12, 15])
arr.searchsorted(9)

3

In [103]:
arr.searchsorted([0, 8, 11, 16])

array([0, 3, 3, 5])

In [104]:
arr = np.array([0, 0, 0, 1, 1, 1, 1])
arr.searchsorted([0, 1])

array([0, 3])

In [105]:
arr.searchsorted([0, 1], side='right')

array([3, 7])

In [106]:
data = np.floor(np.random.uniform(0, 10000, size=50))
bins = np.array([0, 100, 1000, 5000, 10000])
data

array([ 6271.,  6026.,   319.,  9032.,   303.,  5032.,  5423.,  5057.,
        9584.,  1685.,  3526.,  1512.,  5077.,  2314.,  6197.,  1633.,
        5999.,  6985.,  6050.,  1422.,  6029.,   432.,   568.,  6173.,
        8909.,  9904.,  9775.,  2907.,  2329.,  9025.,  7782.,  3410.,
        1408.,  9243.,  4595.,  8738.,  1553.,   951.,  8216.,  7367.,
         165.,  7687.,  8345.,  8352.,  6346.,  5740.,  5529.,  4630.,
        1690.,  7789.])

In [107]:
labels = bins.searchsorted(data)
labels

array([4, 4, 2, 4, 2, 4, 4, 4, 4, 3, 3, 3, 4, 3, 4, 3, 4, 4, 4, 3, 4, 2, 2,
       4, 4, 4, 4, 3, 3, 4, 4, 3, 3, 4, 3, 4, 3, 2, 4, 4, 2, 4, 4, 4, 4, 4,
       4, 3, 3, 4])

In [108]:
Series(data).groupby(labels).mean()

2     456.333333
3    2472.428571
4    7256.066667
dtype: float64

In [109]:
np.digitize(data, bins)

array([4, 4, 2, 4, 2, 4, 4, 4, 4, 3, 3, 3, 4, 3, 4, 3, 4, 4, 4, 3, 4, 2, 2,
       4, 4, 4, 4, 3, 3, 4, 4, 3, 3, 4, 3, 4, 3, 2, 4, 4, 2, 4, 4, 4, 4, 4,
       4, 3, 3, 4])

## 12.7 Numpyの行列クラス

In [111]:
X =  np.array([[ 8.82768214,  3.82222409, -1.14276475,  2.04411587],
               [ 3.82222409,  6.75272284,  0.83909108,  2.08293758],
               [-1.14276475,  0.83909108,  5.01690521,  0.79573241],
               [ 2.04411587,  2.08293758,  0.79573241,  6.24095859]])

In [112]:
# matrix クラス：matlabに近い行列演算の記述ができる
Xm = np.matrix(X)
ym = Xm[:, 0]

In [113]:
Xm

matrix([[ 8.82768214,  3.82222409, -1.14276475,  2.04411587],
        [ 3.82222409,  6.75272284,  0.83909108,  2.08293758],
        [-1.14276475,  0.83909108,  5.01690521,  0.79573241],
        [ 2.04411587,  2.08293758,  0.79573241,  6.24095859]])

In [114]:
X

array([[ 8.82768214,  3.82222409, -1.14276475,  2.04411587],
       [ 3.82222409,  6.75272284,  0.83909108,  2.08293758],
       [-1.14276475,  0.83909108,  5.01690521,  0.79573241],
       [ 2.04411587,  2.08293758,  0.79573241,  6.24095859]])

In [115]:
ym

matrix([[ 8.82768214],
        [ 3.82222409],
        [-1.14276475],
        [ 2.04411587]])

In [116]:
Xm[0,:]

matrix([[ 8.82768214,  3.82222409, -1.14276475,  2.04411587]])

In [117]:
ym.T * Xm * ym

matrix([[ 1195.46796121]])

In [118]:
Xm.I * X

matrix([[  1.00000000e+00,  -1.38777878e-16,  -5.89805982e-17,
           2.77555756e-17],
        [  1.52655666e-16,   1.00000000e+00,   6.24500451e-17,
           2.77555756e-17],
        [  1.11022302e-16,   1.38777878e-17,   1.00000000e+00,
           0.00000000e+00],
        [  5.55111512e-17,   1.11022302e-16,   0.00000000e+00,
           1.00000000e+00]])

## 12.8 配列の入出力：応用編
### 12.8.1 メモリマップファイル

In [119]:
# memmap ： 巨大な配列を扱う
## 巨大ファイルの一部分だけ読み書きする

## まずは、データを入れる箱を用意する
mmap = np.memmap('mymmap', dtype='float64', mode='w+', shape=(10000, 10000))
mmap

memmap([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [120]:
section = mmap[:5]
section

memmap([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [121]:
# データを代入するとメモリにバッファされる
section[:] = np.random.randn(5, 10000)
# ディスクに書き出す時にはflushを呼び出す
mmap.flush()
mmap

memmap([[-1.03215333, -0.33117499, -0.90011033, ..., -0.52449747,
        -0.86370183, -0.2786272 ],
       [-0.31340669,  0.35343624, -0.47788258, ...,  0.86720435,
         1.61642768, -0.34420401],
       [-1.03584699,  0.60156728,  0.66188597, ..., -0.98937636,
         2.02043018,  1.30886881],
       ..., 
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]])

In [122]:
del mmap

In [123]:
mmap = np.memmap('mymmap', dtype='float64', shape=(10000, 10000))
mmap

memmap([[-1.03215333, -0.33117499, -0.90011033, ..., -0.52449747,
        -0.86370183, -0.2786272 ],
       [-0.31340669,  0.35343624, -0.47788258, ...,  0.86720435,
         1.61642768, -0.34420401],
       [-1.03584699,  0.60156728,  0.66188597, ..., -0.98937636,
         2.02043018,  1.30886881],
       ..., 
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]])